version: '3.8'
services:
  gcpn:
    build:
        context: .
        dockerfile : Dockerfile
        shm_size: '84gb'
    shm_size: '84gb'  
    deploy:
      resources:
        limits:
          memory: 10G
          cpus: '0.8'          
        reservations:
          cpus: '0.5'
          memory: 1G
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
    volumes:
      - /home/ubuntu/u75a/u75a-Data-Efficient-Decisions/CybORG/CybORG:/tf/Cage
    ports:
      - 8886:8888 
      - 6005:6006